services:
  nginx:
    #build:
       #context: .  # Usa el directorio actual como contexto de construcción
       #dockerfile: Dockerfile.nginx  # Especifica el Dockerfile unificado
    image: nginx:1.27-alpine    
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - backend1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - school-network
    

  backend1:
    #build:
      #context: .  # Usa el directorio actual como contexto de construcción
      #dockerfile: Dockerfile  # Especifica el Dockerfile unificado
    image: htumba1105/school:latest
    environment:
      - APP_NAME=backend1
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_FOLDER=${AWS_FOLDER}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - ORIGIN=${ORIGIN}
    ports:
      - "3001:3000" 
    networks:
      - school-network 

  backend2:
    #build:
      #context: .  # Usa el directorio actual como contexto de construcción
      #dockerfile: Dockerfile  # Especifica el Dockerfile unificado
    image: htumba1105/school:latest
    environment:
      - APP_NAME=backend2
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_FOLDER=${AWS_FOLDER}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - ORIGIN=${ORIGIN}
    ports:
      - "3002:3000" 
    networks:
      - school-network 

  backend3:
    #build:
      #context: .  # Usa el directorio actual como contexto de construcción
      #dockerfile: Dockerfile  # Especifica el Dockerfile unificado
    image: htumba1105/school:latest
    environment:
      - APP_NAME=backend3
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_FOLDER=${AWS_FOLDER}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - ORIGIN=${ORIGIN}
    ports:
      - "3003:3000" 
    networks:
      - school-network       

networks:
  school-network:
    driver: bridge
    name: school-network