worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
        
    # Upstream block to define the Node.js backend servers
    upstream nodejs_cluster {        
        server backend1:3000;
        server backend2:3000;
        server backend3:3000;
    }

    # Optional server block for HTTP to HTTPS redirection
    server {
        listen 8080;  # Listen on port 80 for HTTP
        server_name localhost;

        # Redirect all HTTP traffic to HTTPS
        location / {
            proxy_pass http://nodejs_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            #return 301 https://$host$request_uri;
        }
    }
}

