name: Deploy Docker to AWS - CICD

on:
  push:
    branches: [test]
    #paths:
      #- 'backend/**'  # Solo activa el flujo de trabajo si hay cambios en la carpeta 'backend'

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t htumba1105/school ./backend
      - name: Publish image to docker hub
        run: docker push htumba1105/school:latest
        
  deploy:
    needs: build
    runs-on: [aws_ec2]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create certbot directories
        run: |
          mkdir -p certbot/{www,conf}
          chmod -R 777 certbot

      - name: Start Nginx for Certbot challenge
        run: |
          docker-compose up -d nginx
          sleep 10  # Esperar a que Nginx esté listo

      - name: Generate SSL certificates
        run: |
          docker-compose run --rm certbot certonly --webroot -w /var/www/certbot \
            --email htumba1105@gmail.com \
            --agree-tos --no-eff-email \
            -d nomadas.infy.uk

      - name: Full deployment
        run: |
          docker-compose down
          docker-compose up -d