name: Deploy Docker to AWS - CICD

on:
  push:
    branches: [test]
    #paths:
      #- 'backend/**'  # Solo activa el flujo de trabajo si hay cambios en la carpeta 'backend'

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t htumba1105/school ./backend
      - name: Publish image to docker hub
        run: docker push htumba1105/school:latest
        
  deploy:
    needs: build
    runs-on: [aws_ec2]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          clean: false  # Evita la limpieza del repositorio
          path: /home/ubuntu/actions-runner/backend/School-Management/School-Management

      - name: Check and clean certbot directory
        run: |
          if [ -d "/home/ubuntu/actions-runner/backend/School-Management/School-Management/backend/certbot/conf" ]; then
            echo "Certbot directory exists, checking certificates..."
            if ! openssl x509 -checkend 86400 -noout -in /home/ubuntu/actions-runner/backend/School-Management/School-Management/backend/certbot/conf/live/nomadas.infy.uk/fullchain.pem; then
              echo "Certificates are expired or will expire soon, cleaning directory..."
              sudo rm -rf /home/ubuntu/actions-runner/backend/School-Management/School-Management/backend/certbot/conf
            else
              echo "Certificates are valid, skipping cleanup."
            fi
          else
            echo "Certbot directory does not exist, creating it..."
          fi
          mkdir -p /home/ubuntu/actions-runner/backend/School-Management/School-Management/backend/certbot/conf
          chmod -R 755 /home/ubuntu/actions-runner/backend/School-Management/School-Management/backend/certbot

      - name: Start Nginx for Certbot challenge
        working-directory: ./backend
        run: |
          sudo docker-compose up -d nginx
          sleep 10  # Esperar a que Nginx esté listo

      - name: Generate SSL certificates
        working-directory: ./backend
        run: |
          sudo docker-compose run --rm certbot certonly --webroot -w /var/www/certbot \
            --email htumba1105@gmail.com \
            --agree-tos --no-eff-email \
            -d nomadas.infy.uk

      - name: Full deployment
        working-directory: ./backend
        run: |
          sudo docker-compose down
          sudo docker-compose up -d
      - name: Clean certbot directory
        run: |
          docker run --rm -v /home/ubuntu/actions-runner/backend/School-Management/School-Management/backend/certbot:/certbot alpine sh -c "rm -rf /certbot/conf && mkdir -p /certbot/conf && chmod -R 755 /certbot"
