name: Deploy Docker to AWS - CICD

on:
  push:
    branches: [test]
    #paths:
      #- 'backend/**'  # Solo activa el flujo de trabajo si hay cambios en la carpeta 'backend'

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t htumba1105/school ./backend
      - name: Publish image to docker hub
        run: docker push htumba1105/school:latest
        
  deploy:
    needs: build
    runs-on: [aws_ec2]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Stop docker-compose
        working-directory: ./backend
        run: sudo docker-compose down -v --remove-orphans 
      - name: Remove old school image
        run: |
          if docker images -q htumba1105/school:latest; then
            docker rmi htumba1105/school:latest
          fi
      - name: Pull new school image
        run: docker pull htumba1105/school:latest
      - name: Full deployment
        working-directory: ./backend
        run: sudo docker-compose up -d